name: Cloudflare Deploy

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4
      - name: Setup Wrangler Config
        run: |
          echo "Copying wrangler.jsonc..."
          echo "${{ secrets.CLOUDFLARE_WRANGLER_CONFIG }}" | base64 --decode > wrangler.jsonc
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          wranglerVersion: '3.109.2'
          preCommands: |
            echo "Migrating database..."
            pnpm run db:migrate -- --remote
            echo "Migration complete."
          postCommands: |
            echo "*** post commands ***"
          secrets: |
            ADMIN_USERNAME
            ADMIN_PASSWORD
        env:
          ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
